### PR TITLE
1220935 - fix module-retailer - compatibility Magento 2.4.6 and PHP8.2

### PR DESCRIPTION
**Pull request by livca-smile**
Dataset compatibility ES 2.11.x and PHP 8.2

- fix Dynamic type declaration
- fix Type hinting
- Replace `Zend_Date` by `DateTime`
- Remove `MutationObserver` support
- fix UI Component Retailer Offer editing
- Replace `Zend_Validate` by `Laminas\Validator`
- fix Retailer Grid Column Action
- fix Retailer Grid Mass Actions
- fix some translations
- remove Temando/Shipping Plugin

### CODE REVIEW

**Comment by Skistims** [comment]
Hello,
sorry to jump into your PR!
The Magento 2.4.6 compatibility of this module and its dependencies is critical for the update of a project I am maintaining. Before I start forking multiple projects and start fixing it on my own, I wanted to give it a try:
Is there an ETA for this merge?
Can I help you somehow?

**Comment by livca-smile** [comment]
Hi @Skistims 

This branch is still in progress.
As an estimation, it should be finished in end of June.

Best regards,
livca

**Comment by samc2810** [comment]
@livca-smile 
any updates here?

Cheers

**Comment by Skistims** [comment]
> Hi @Skistims
> 
> This branch is still in progress. As an estimation, it should be finished in end of June.
> 
> Best regards, livca

@livca-smile 
Is there an update on this?

**Pull request merged**
